In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from keras import models
from keras import layers
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('train.csv').dropna()

In [4]:
df.shape

(1216, 4098)

In [5]:
df.head()

ID   n0        n1        n2        n3        n4        n5        n6  n7  \
0   0  0.0  0.000000  1.272801  0.290501  0.581446  0.000000  0.000000   0   
1   1  0.0  0.000000  1.542096  0.000000  0.896557  0.049978  0.000000   0   
2   2  0.0  0.000000  1.098595  0.571866  0.500355  0.000000  0.000000   0   
3   3  0.0  0.101666  1.159194  0.599216  0.893206  0.000000  0.200139   0   
4   4  0.0  0.000000  1.178603  0.362568  0.577602  0.000000  0.000000   0   

         n8  ...     n4087     n4088     n4089     n4090     n4091     n4092  \
0  0.000000  ...  1.645888  0.869640  0.302432  0.953719  0.022545  0.498048   
1  0.117847  ...  1.504220  0.622686  0.588427  0.524415  0.305426  0.386204   
2  0.493137  ...  1.169341  0.913239  0.064404  0.531270  0.000000  0.471604   
3  0.645675  ...  0.560686  1.243676  0.432523  0.701881  0.000000  0.589985   
4  0.079862  ...  1.206032  0.736831  0.345906  0.878515  0.119000  0.261441   

   n4093     n4094     n4095     category  
0    0.0  0.034988  0.692382  Orange_Ripe  
1    0.0  0.000000  0.668196  Banana_Ripe  
2    0.0  0.000000  0.658250    Mango_Raw  
3    0.0  0.000000  0.591165   Leeche_Raw  
4    0.0  0.000000  0.458905   Mango_Ripe  

[5 rows x 4098 columns]

In [6]:
df['category'].value_counts()/df['category'].shape

Banana_Ripe          0.070724
Apple_Ripe           0.066612
Apple_Raw            0.064145
Papaya_Ripe          0.063322
Strawberry_Ripe      0.061678
Mango_Raw            0.059211
Strawberry_Raw       0.053454
Banana_Raw           0.051809
Coconut_Ripe         0.047697
Pomengranate_Raw     0.047697
Pomengranate_Ripe    0.046875
Guava_Ripe           0.046053
Leeche_Ripe          0.045230
Coconut_Raw          0.044408
Orange_Ripe          0.044408
Papaya_Raw           0.041941
Orange_Raw           0.039474
Mango_Ripe           0.037829
Guava_Raw            0.037007
Leeche_Raw           0.030428
Name: category, dtype: float64

In [8]:
X = df.drop('category',axis=1)
y = df['category']

In [9]:
X

ID        n0        n1        n2        n3        n4        n5  \
0        0  0.000000  0.000000  1.272801  0.290501  0.581446  0.000000   
1        1  0.000000  0.000000  1.542096  0.000000  0.896557  0.049978   
2        2  0.000000  0.000000  1.098595  0.571866  0.500355  0.000000   
3        3  0.000000  0.101666  1.159194  0.599216  0.893206  0.000000   
4        4  0.000000  0.000000  1.178603  0.362568  0.577602  0.000000   
...    ...       ...       ...       ...       ...       ...       ...   
1211  1211  0.000000  0.364963  0.770978  0.570945  0.996824  0.066661   
1212  1212  0.083656  0.111407  1.753287  0.000000  1.197256  0.117919   
1213  1213  0.000000  0.000000  1.545725  0.000000  0.842485  0.000000   
1214  1214  0.000000  0.000000  1.194037  0.969926  0.499340  0.055789   
1215  1215  0.000000  0.000000  1.020402  1.107121  0.361440  0.000000   

            n6  n7        n8  ...     n4086     n4087     n4088     n4089  \
0     0.000000   0  0.000000  ...  0.162282  1.645888  0.869640  0.302432   
1     0.000000   0  0.117847  ...  0.273422  1.504220  0.622686  0.588427   
2     0.000000   0  0.493137  ...  0.000000  1.169341  0.913239  0.064404   
3     0.200139   0  0.645675  ...  0.585878  0.560686  1.243676  0.432523   
4     0.000000   0  0.079862  ...  0.250886  1.206032  0.736831  0.345906   
...        ...  ..       ...  ...       ...       ...       ...       ...   
1211  0.000000   0  0.727390  ...  1.050548  0.317000  0.844568  0.084291   
1212  0.000000   0  0.000000  ...  0.555139  1.114398  0.659943  0.000000   
1213  0.000000   0  0.087607  ...  0.238965  1.490054  0.883849  0.589065   
1214  0.000000   0  0.221447  ...  0.000000  0.987144  0.645109  0.113367   
1215  0.000000   0  0.026102  ...  0.504208  0.823649  0.879483  0.406130   

         n4090     n4091     n4092     n4093     n4094     n4095  
0     0.953719  0.022545  0.498048  0.000000  0.034988  0.692382  
1     0.524415  0.305426  0.386204  0.000000  0.000000  0.668196  
2     0.531270  0.000000  0.471604  0.000000  0.000000  0.658250  
3     0.701881  0.000000  0.589985  0.000000  0.000000  0.591165  
4     0.878515  0.119000  0.261441  0.000000  0.000000  0.458905  
...        ...       ...       ...       ...       ...       ...  
1211  0.399840  0.225693  0.214918  0.000000  0.000000  0.356400  
1212  0.457870  0.405808  0.000000  0.342428  0.000000  0.019390  
1213  0.644103  0.194427  0.426330  0.000000  0.000000  0.764020  
1214  0.877268  0.000000  0.175457  0.000000  0.000000  0.367878  
1215  0.734420  0.000000  0.075351  0.000000  0.000000  0.316971  

[1216 rows x 4097 columns]

In [10]:
y

0           Orange_Ripe
1           Banana_Ripe
2             Mango_Raw
3            Leeche_Raw
4            Mango_Ripe
             ...       
1211    Strawberry_Ripe
1212        Banana_Ripe
1213        Banana_Ripe
1214         Guava_Ripe
1215         Guava_Ripe
Name: category, Length: 1216, dtype: object

In [11]:
encoder = OneHotEncoder()

In [12]:
encoded_Y = encoder.fit(y.values.reshape(-1,1))
encoded_Y = encoded_Y.transform(y.values.reshape(-1,1)).toarray()
encoded_Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
encoded_Y.shape

(1216, 20)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,encoded_Y,test_size = 0.2,random_state =22)

In [15]:
sc = StandardScaler()
X_train_new = sc.fit_transform(X_train)
X_test_new = sc.transform(X_test)

In [16]:
pca = PCA(n_components= 100)
X_train_trans = pca.fit_transform(X_train_new)
X_test_trans = pca.transform(X_test_new)
X_train_trans.shape

(972, 100)

In [17]:
pca.explained_variance_ratio_.cumsum()

array([0.12022106, 0.1946782 , 0.25654385, 0.30530954, 0.34413905,
       0.38098896, 0.41391999, 0.44155896, 0.46440084, 0.48428964,
       0.50252907, 0.51910041, 0.53368665, 0.54786798, 0.56011925,
       0.57139735, 0.58168122, 0.59152934, 0.60085451, 0.60963581,
       0.61814793, 0.62624749, 0.63365772, 0.6408278 , 0.64789931,
       0.65419272, 0.66014462, 0.66580551, 0.67135468, 0.67674998,
       0.68177839, 0.68673643, 0.69152645, 0.69585588, 0.7000149 ,
       0.70412552, 0.70808323, 0.71195619, 0.71565029, 0.71933782,
       0.72295181, 0.72642091, 0.7297542 , 0.73296525, 0.7361584 ,
       0.73923056, 0.74225744, 0.74516638, 0.74798934, 0.75074379,
       0.75346706, 0.75609142, 0.75868544, 0.7611553 , 0.76358705,
       0.76599251, 0.7683423 , 0.77062872, 0.77286871, 0.77508814,
       0.77724894, 0.77938388, 0.78148929, 0.78356449, 0.78557798,
       0.78756676, 0.78949542, 0.79137596, 0.7932514 , 0.79511568,
       0.79692065, 0.79868233, 0.80040027, 0.80210413, 0.80378

In [18]:
input_shape = X_train_trans.shape[1]
n_batch_size = 20
n_steps_per_epoch = int(X_train_trans.shape[0] / n_batch_size)
n_test_steps = int(X_test_trans.shape[0] / n_batch_size)
n_epochs = 25
num_classes = y_train.shape[1]

In [19]:
num_classes

20

In [34]:
model = models.Sequential()

In [35]:
model.add(layers.Dense(12, activation='relu', input_shape=(input_shape,)))

In [36]:
model.add(layers.Dense(12, activation='relu'))

In [37]:
model.add(layers.Dense(num_classes, activation='softmax'))

In [38]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 12)                1212      
                                                                 
 dense_7 (Dense)             (None, 12)                156       
                                                                 
 dense_8 (Dense)             (None, 20)                260       
                                                                 
Total params: 1,628
Trainable params: 1,628
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
history = model.fit(X_train_trans, y_train, steps_per_epoch=n_steps_per_epoch, epochs=n_epochs, batch_size=n_batch_size)

Epoch 1/25
48/48 [==============================] - 1s 3ms/step - loss: 4.8272 - accuracy: 0.0802
Epoch 2/25
48/48 [==============================] - 0s 3ms/step - loss: 3.6018 - accuracy: 0.1145
Epoch 3/25
48/48 [==============================] - 0s 3ms/step - loss: 3.0442 - accuracy: 0.1408
Epoch 4/25
48/48 [==============================] - 0s 3ms/step - loss: 2.8090 - accuracy: 0.1817
Epoch 5/25
48/48 [==============================] - 0s 3ms/step - loss: 2.6176 - accuracy: 0.2153
Epoch 6/25
48/48 [==============================] - 0s 3ms/step - loss: 2.4967 - accuracy: 0.2384
Epoch 7/25
48/48 [==============================] - 0s 3ms/step - loss: 2.3201 - accuracy: 0.2857
Epoch 8/25
48/48 [==============================] - 0s 2ms/step - loss: 2.2679 - accuracy: 0.2973
Epoch 9/25
48/48 [==============================] - 0s 3ms/step - loss: 2.0980 - accuracy: 0.3382
Epoch 10/25
48/48 [==============================] - 0s 4ms/step - loss: 2.0695 - accuracy: 0.3382
Epoch 11/25
48/48 [

In [63]:
y_pred = model.predict(X_test_trans)

8/8 [==============================] - 0s 4ms/step


In [64]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [65]:
re_transformed_y_pred = encoder.inverse_transform(y_pred)

In [66]:
re_transformed_y_pred

array([['Guava_Ripe'],
       ['Coconut_Ripe'],
       ['Orange_Ripe'],
       ['Guava_Ripe'],
       ['Coconut_Ripe'],
       ['Orange_Ripe'],
       ['Guava_Ripe'],
       ['Orange_Raw'],
       ['Pomengranate_Ripe'],
       ['Strawberry_Raw'],
       ['Mango_Raw'],
       ['Apple_Ripe'],
       ['Pomengranate_Ripe'],
       ['Guava_Raw'],
       ['Strawberry_Ripe'],
       ['Pomengranate_Ripe'],
       ['Banana_Raw'],
       ['Guava_Raw'],
       ['Orange_Raw'],
       ['Leeche_Ripe'],
       ['Leeche_Raw'],
       ['Mango_Raw'],
       ['Banana_Raw'],
       ['Mango_Raw'],
       ['Banana_Ripe'],
       ['Strawberry_Raw'],
       ['Strawberry_Ripe'],
       ['Mango_Raw'],
       ['Apple_Raw'],
       ['Strawberry_Raw'],
       ['Orange_Raw'],
       ['Strawberry_Ripe'],
       ['Leeche_Ripe'],
       ['Pomengranate_Ripe'],
       ['Mango_Raw'],
       ['Coconut_Raw'],
       ['Coconut_Ripe'],
       ['Strawberry_Ripe'],
       ['Strawberry_Raw'],
       ['Strawberry_Raw'],
       [

In [67]:
re_transformed_y_test = encoder.inverse_transform(y_test)

In [68]:
re_transformed_y_test

array([['Papaya_Ripe'],
       ['Coconut_Ripe'],
       ['Orange_Ripe'],
       ['Guava_Raw'],
       ['Papaya_Raw'],
       ['Orange_Ripe'],
       ['Guava_Ripe'],
       ['Mango_Raw'],
       ['Pomengranate_Ripe'],
       ['Coconut_Ripe'],
       ['Apple_Raw'],
       ['Apple_Ripe'],
       ['Pomengranate_Ripe'],
       ['Guava_Raw'],
       ['Strawberry_Ripe'],
       ['Pomengranate_Ripe'],
       ['Papaya_Raw'],
       ['Guava_Raw'],
       ['Apple_Raw'],
       ['Leeche_Ripe'],
       ['Strawberry_Raw'],
       ['Apple_Raw'],
       ['Mango_Raw'],
       ['Mango_Raw'],
       ['Banana_Ripe'],
       ['Strawberry_Raw'],
       ['Strawberry_Ripe'],
       ['Pomengranate_Raw'],
       ['Apple_Raw'],
       ['Strawberry_Ripe'],
       ['Papaya_Raw'],
       ['Strawberry_Ripe'],
       ['Leeche_Ripe'],
       ['Pomengranate_Ripe'],
       ['Coconut_Raw'],
       ['Coconut_Raw'],
       ['Coconut_Ripe'],
       ['Strawberry_Ripe'],
       ['Strawberry_Ripe'],
       ['Strawberry_Raw'],


In [69]:
from sklearn.metrics import accuracy_score

In [70]:
accuracy_score(re_transformed_y_test,re_transformed_y_pred)

0.6516393442622951