In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Heart.csv')

In [4]:
df

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [5]:
df.isnull().sum().sum()

6

In [6]:
df = df.dropna()

In [7]:
df

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
297         298   57    0  asymptomatic     140   241    0        0    123   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
297      1      0.2      2  0.0  reversable  Yes  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  

[297 rows x 15 columns]

In [8]:
df['AHD'].unique()

array(['No', 'Yes'], dtype=object)

In [9]:
df = df.iloc[:,1:15]

In [10]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['ChestPain'] = label_encoder.fit_transform(df['ChestPain'])
df['Thal'] = label_encoder.fit_transform(df['Thal'])
df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0     0   No  
1        2  3.0     1  Yes  
2        2  2.0     2  Yes  
3        3  0.0     1   No  
4        1  0.0     1   No  
..     ...  ...   ...  ...  
297      2  0.0     2  Yes  
298      2  0.0     2  Yes  
299      2  2.0     2  Yes  
300      2  1.0     2  Yes  
301      2  1.0     1  Yes  

[297 rows x 14 columns]

In [11]:
mean_values_yes = df.groupby('AHD').mean().loc['Yes']

In [12]:
mean_values_yes

Age           56.759124
Sex            0.817518
ChestPain      0.416058
RestBP       134.635036
Chol         251.854015
Fbs            0.145985
RestECG        1.175182
MaxHR        139.109489
ExAng          0.540146
Oldpeak        1.589051
Slope          1.824818
Ca             1.145985
Thal           1.554745
Name: Yes, dtype: float64

In [13]:
mean_values_no = df.groupby('AHD').mean().loc['No']

In [14]:
mean_values_no

Age           52.64375
Sex            0.55625
ChestPain      1.20625
RestBP       129.17500
Chol         243.49375
Fbs            0.14375
RestECG        0.84375
MaxHR        158.58125
ExAng          0.14375
Oldpeak        0.59875
Slope          1.41250
Ca             0.27500
Thal           1.13125
Name: No, dtype: float64

In [15]:
new_df = df.iloc[:,:13]

In [16]:
new_df_1 = df[df['AHD']=='Yes']
new_df_1

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
6     62    0          0     140   268    0        2    160      0      3.6   
8     63    1          0     130   254    0        2    147      0      1.4   
9     53    1          0     140   203    1        2    155      1      3.1   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  AHD  
1        2  3.0     1  Yes  
2        2  2.0     2  Yes  
6        3  2.0     1  Yes  
8        2  1.0     2  Yes  
9        3  0.0     2  Yes  
..     ...  ...   ...  ...  
297      2  0.0     2  Yes  
298      2  0.0     2  Yes  
299      2  2.0     2  Yes  
300      2  1.0     2  Yes  
301      2  1.0     1  Yes  

[137 rows x 14 columns]

In [17]:
new_df_1 = new_df_1.iloc[:,:13]
new_df_1

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
6     62    0          0     140   268    0        2    160      0      3.6   
8     63    1          0     130   254    0        2    147      0      1.4   
9     53    1          0     140   203    1        2    155      1      3.1   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  
1        2  3.0     1  
2        2  2.0     2  
6        3  2.0     1  
8        2  1.0     2  
9        3  0.0     2  
..     ...  ...   ...  
297      2  0.0     2  
298      2  0.0     2  
299      2  2.0     2  
300      2  1.0     2  
301      2  1.0     1  

[137 rows x 13 columns]

In [18]:
new_df_2 = df[df['AHD']=='No']
new_df_2 = new_df_2.iloc[:,:13]
new_df_2

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
5     56    1          2     120   236    0        0    178      0      0.8   
7     57    0          0     120   354    0        0    163      1      0.6   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
283   35    1          2     122   192    0        0    174      0      0.0   
288   56    1          2     130   221    0        2    163      0      0.0   
289   56    1          2     120   240    0        0    169      0      0.0   
291   55    0          2     132   342    0        0    166      0      1.2   
295   41    1          2     120   157    0        0    182      0      0.0   

     Slope   Ca  Thal  
0        3  0.0     0  
3        3  0.0     1  
4        1  0.0     1  
5        1  0.0     1  
7        1  0.0     1  
..     ...  ...   ...  
283      1  0.0     1  
288      1  0.0     2  
289      3  0.0     1  
291      1  0.0     1  
295      1  0.0     1  

[160 rows x 13 columns]

In [19]:
cov_new_df1 = new_df_1.cov()

In [20]:
cov_new_df1


Age       Sex  ChestPain      RestBP         Chol       Fbs  \
Age        62.404787 -0.426632   0.071544   36.190854    43.891048  0.314835   
Sex        -0.426632  0.150279   0.039717   -2.199442    -4.468012 -0.017282   
ChestPain   0.071544  0.039717   0.685917    1.079433     0.120009 -0.002362   
RestBP     36.190854 -2.199442   1.079433  357.086410   133.166917  1.509553   
Chol       43.891048 -4.468012   0.120009  133.166917  2468.096179  1.109704   
Fbs         0.314835 -0.017282  -0.002362    1.509553     1.109704  0.125590   
RestECG     0.851331 -0.004562  -0.051363    2.351170     5.466939  0.033061   
MaxHR     -22.554315 -0.744579   4.792347    7.047606    65.310219  0.130957   
ExAng      -0.155700 -0.003650  -0.160208    0.323583     1.836786  0.008802   
Oldpeak     0.865726 -0.032895  -0.164529    2.821710    -1.484698  0.010434   
Slope       0.383963 -0.032203  -0.044225    1.487065    -0.356644  0.018409   
Ca          2.947188 -0.017282  -0.105303    0.730142     5.197939  0.059414   
Thal       -0.608040  0.013740  -0.056033    0.211303     1.338933 -0.022757   

            RestECG       MaxHR     ExAng   Oldpeak     Slope        Ca  \
Age        0.851331  -22.554315 -0.155700  0.865726  0.383963  2.947188   
Sex       -0.004562   -0.744579 -0.003650 -0.032895 -0.032203 -0.017282   
ChestPain -0.051363    4.792347 -0.160208 -0.164529 -0.044225 -0.105303   
RestBP     2.351170    7.047606  0.323583  2.821710  1.487065  0.730142   
Chol       5.466939   65.310219  1.836786 -1.484698 -0.356644  5.197939   
Fbs        0.033061    0.130957  0.008802  0.010434  0.018409  0.059414   
RestECG    0.954380    1.046855 -0.021790  0.021785 -0.005850  0.158061   
MaxHR      1.046855  515.774689 -3.412516 -6.453204 -4.642443 -1.788160   
ExAng     -0.021790   -3.412516  0.250215  0.123605  0.058555 -0.035316   
Oldpeak    0.021785   -6.453204  0.123605  1.703041  0.426744  0.242051   
Slope     -0.005850   -4.642443  0.058555  0.426744  0.322027 -0.003650   
Ca         0.158061   -1.788160 -0.035316  0.242051 -0.003650  1.037355   
Thal      -0.053778    1.299109  0.029036  0.087736 -0.005045 -0.052168   

               Thal  
Age       -0.608040  
Sex        0.013740  
ChestPain -0.056033  
RestBP     0.211303  
Chol       1.338933  
Fbs       -0.022757  
RestECG   -0.053778  
MaxHR      1.299109  
ExAng      0.029036  
Oldpeak    0.087736  
Slope     -0.005045  
Ca        -0.052168  
Thal       0.425290

In [21]:
cov_new_df2 = new_df_2.cov()
cov_new_df2

Age       Sex  ChestPain      RestBP         Chol       Fbs  \
Age         91.224489 -0.863483  -0.347445   45.540723   124.007193  0.510653   
Sex         -0.863483  0.248388   0.054363    0.191352    -6.175747  0.026454   
ChestPain   -0.347445  0.054363   0.856564    2.259277    -3.769143  0.039347   
RestBP      45.540723  0.191352   2.259277  268.107547    91.076572  0.811164   
Chol       124.007193 -6.175747  -3.769143   91.076572  2889.874175 -0.524253   
Fbs          0.510653  0.026454   0.039347    0.811164    -0.524253  0.123860   
RestECG      1.151533 -0.006879   0.051297    2.058962     9.932980  0.016313   
MaxHR      -96.011753  1.787854   2.740998    6.067453    19.535102 -0.209866   
ExAng        0.139583  0.013876  -0.036124   -0.245440    -0.411046 -0.008215   
Oldpeak      1.240432  0.016423   0.078247    2.451164     1.783640 -0.003593   
Slope        0.544104 -0.004481   0.021305    0.160063    -1.846462  0.003223   
Ca           1.545126 -0.015566   0.012107    0.209434     2.712421  0.041981   
Thal         0.323781  0.046030   0.004206   -0.079717     1.752398  0.012461   

            RestECG       MaxHR     ExAng   Oldpeak     Slope        Ca  \
Age        1.151533  -96.011753  0.139583  1.240432  0.544104  1.545126   
Sex       -0.006879    1.787854  0.013876  0.016423 -0.004481 -0.015566   
ChestPain  0.051297    2.740998 -0.036124  0.078247  0.021305  0.012107   
RestBP     2.058962    6.067453 -0.245440  2.451164  0.160063  0.209434   
Chol       9.932980   19.535102 -0.411046  1.783640 -1.846462  2.712421   
Fbs        0.016313   -0.209866 -0.008215 -0.003593  0.003223  0.041981   
RestECG    0.975432   -0.971502  0.028892  0.074646  0.096305 -0.044811   
MaxHR     -0.971502  362.647445 -1.209866 -2.843294 -2.580896 -1.374686   
ExAng      0.028892   -1.209866  0.123860  0.007099  0.009513 -0.008333   
Oldpeak    0.074646   -2.843294  0.007099  0.619621  0.222531 -0.007201   
Slope      0.096305   -2.580896  0.009513  0.222531  0.357075 -0.044969   
Ca        -0.044811   -1.374686 -0.008333 -0.007201 -0.044969  0.401887   
Thal      -0.035967   -0.101926  0.012461  0.000794 -0.010456  0.026572   

               Thal  
Age        0.323781  
Sex        0.046030  
ChestPain  0.004206  
RestBP    -0.079717  
Chol       1.752398  
Fbs        0.012461  
RestECG   -0.035967  
MaxHR     -0.101926  
ExAng      0.012461  
Oldpeak    0.000794  
Slope     -0.010456  
Ca         0.026572  
Thal       0.190212

In [22]:
Sw = 137*cov_new_df1 + 160*cov_new_df2
Sw

Age          Sex    ChestPain        RestBP  \
Age        23145.374121  -196.605762   -45.789724  12244.662782   
Sex         -196.605762    60.330374    14.139290   -270.707177   
ChestPain    -45.789724    14.139290   231.020903    509.366630   
RestBP     12244.662782  -270.707177   509.366630  91818.045782   
Chol       25854.224473 -1600.237144  -586.621717  32816.119219   
Fbs          124.836755     1.865057     5.972068    336.594987   
RestECG      300.877636    -1.725629     1.170782    651.544256   
MaxHR     -18451.821680   184.049251  1095.111219   1936.314512   
ExAng          1.002451     1.720126   -27.728404      5.060442   
Oldpeak      317.073594    -1.878945   -10.020944    778.760428   
Slope        139.659545    -5.128746    -2.650018    229.338004   
Ca           650.984832    -4.858213   -12.489364    133.538846   
Thal         -31.496439     9.247133    -7.003515     16.193812   

                    Chol         Fbs      RestECG          MaxHR       ExAng  \
Age         25854.224473  124.836755   300.877636  -18451.821680    1.002451   
Sex         -1600.237144    1.865057    -1.725629     184.049251    1.720126   
ChestPain    -586.621717    5.972068     1.170782    1095.111219  -27.728404   
RestBP      32816.119219  336.594987   651.544256    1936.314512    5.060442   
Chol       800509.044395   68.148909  2338.247318   12073.116352  185.872410   
Fbs            68.148909   37.023492     7.139475     -15.637440   -0.108583   
RestECG      2338.247318    7.139475   286.819182     -12.021134    1.637347   
MaxHR       12073.116352  -15.637440   -12.021134  128684.723548 -661.093322   
ExAng         185.872410   -0.108583     1.637347    -661.093322   54.097022   
Oldpeak        81.978713    0.854569    14.927955   -1339.016015   18.069673   
Slope        -344.294256    3.037782    14.607334   -1048.958102    9.544071   
Ca           1146.105068   14.856687    14.484600    -464.927627   -6.171569   
Thal          463.817471   -1.123936   -13.122364     161.669765    5.971652   

               Oldpeak        Slope           Ca        Thal  
Age         317.073594   139.659545   650.984832  -31.496439  
Sex          -1.878945    -5.128746    -4.858213    9.247133  
ChestPain   -10.020944    -2.650018   -12.489364   -7.003515  
RestBP      778.760428   229.338004   133.538846   16.193812  
Chol         81.978713  -344.294256  1146.105068  463.817471  
Fbs           0.854569     3.037782    14.856687   -1.123936  
RestECG      14.927955    14.607334    14.484600  -13.122364  
MaxHR     -1339.016015 -1048.958102  -464.927627  161.669765  
ExAng        18.069673     9.544071    -6.171569    5.971652  
Oldpeak     332.455989    94.069002    32.008828   12.146897  
Slope        94.069002   101.249723    -7.694969   -2.364132  
Ca           32.008828    -7.694969   206.419534   -2.895486  
Thal         12.146897    -2.364132    -2.895486   88.698668

In [23]:
# Sw inverse calc
Sw = np.linalg.inv(Sw)
Sw.shape

(13, 13)

In [24]:
mean_diff = mean_values_yes - mean_values_no

In [25]:
mean_diff.shape

(13,)

In [26]:
W = np.dot(Sw,mean_diff)

In [27]:
W

array([-3.62048978e-05,  5.58228349e-03, -2.55228583e-03,  7.52126980e-05,
        8.49410275e-06, -2.37752247e-03,  8.23034451e-04, -8.39692813e-05,
        4.05045444e-03,  9.60661231e-04,  2.42112623e-03,  4.25703909e-03,
        3.96395796e-03])

In [28]:
W.shape

(13,)

In [29]:
new_df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  
0        3  0.0     0  
1        2  3.0     1  
2        2  2.0     2  
3        3  0.0     1  
4        1  0.0     1  
..     ...  ...   ...  
297      2  0.0     2  
298      2  0.0     2  
299      2  2.0     2  
300      2  1.0     2  
301      2  1.0     1  

[297 rows x 13 columns]

In [30]:
projections = np.dot(new_df,W)

In [31]:
projections

array([ 0.00467554,  0.03726606,  0.03277368,  0.01247899, -0.00014516,
        0.00168745,  0.02197227,  0.0072937 ,  0.02291125,  0.02439061,
        0.00847831,  0.00474884,  0.01402572,  0.00596653,  0.01062308,
        0.00698672,  0.01100354,  0.01028988,  0.00272889,  0.00334349,
        0.00981431, -0.00305974,  0.00856206,  0.02181749,  0.03313984,
        0.00359932, -0.00079628,  0.00730775,  0.01087275,  0.02464152,
        0.00635386,  0.02260941,  0.00720612,  0.01531897,  0.00898306,
        0.00794967,  0.02534648,  0.02311253,  0.02766402,  0.01410348,
        0.02941528,  0.00949522,  0.00860453,  0.00633801,  0.00421255,
        0.01852758,  0.00757667,  0.0232839 ,  0.00666224,  0.01144747,
       -0.00047452,  0.01273555,  0.01431727,  0.00276748,  0.02324653,
        0.03089756,  0.01764527,  0.01256023,  0.01764285,  0.01447722,
        0.01657168,  0.01279965,  0.03729564, -0.00203864,  0.02313324,
        0.03445815,  0.01327791,  0.01400471,  0.0313998 ,  0.01

In [32]:
projections.shape

(297,)

In [33]:
X = projections
y = df['AHD'].to_numpy()

In [34]:
y

array(['No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No',

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 22)

In [37]:
X_train.shape

(237,)

In [38]:
weights = np.zeros((2,))

In [39]:
weights.shape

(2,)

In [40]:
ones = np.ones((237,))

In [41]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [42]:
X_new = np.c_[ones,X_train]

In [43]:
X_new

array([[ 1.00000000e+00,  1.09803305e-02],
       [ 1.00000000e+00,  7.57667196e-03],
       [ 1.00000000e+00,  2.67536151e-04],
       [ 1.00000000e+00,  2.29882695e-02],
       [ 1.00000000e+00,  1.59069692e-02],
       [ 1.00000000e+00,  1.80002341e-02],
       [ 1.00000000e+00,  2.22832593e-02],
       [ 1.00000000e+00,  1.55502970e-03],
       [ 1.00000000e+00,  1.40047073e-02],
       [ 1.00000000e+00,  3.27736804e-02],
       [ 1.00000000e+00,  2.64469231e-02],
       [ 1.00000000e+00,  1.52454567e-02],
       [ 1.00000000e+00, -1.08170379e-04],
       [ 1.00000000e+00,  3.45713955e-02],
       [ 1.00000000e+00,  8.52437915e-03],
       [ 1.00000000e+00,  7.13846801e-03],
       [ 1.00000000e+00,  2.57025682e-02],
       [ 1.00000000e+00,  1.63624032e-02],
       [ 1.00000000e+00,  1.05527718e-02],
       [ 1.00000000e+00,  8.04036437e-03],
       [ 1.00000000e+00,  5.13715925e-03],
       [ 1.00000000e+00,  1.14474729e-02],
       [ 1.00000000e+00,  2.06303317e-02],
       [ 1.

In [44]:
X_new.shape

(237, 2)

In [45]:
iter = 800

In [46]:
alpha = 0.001

In [47]:
lr = preprocessing.LabelEncoder()
y_train = lr.fit_transform(y_train)

In [48]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [49]:
from numpy import exp
for i in range(iter):
    z = np.dot(X_new,weights)
    p = 1/(1+exp(-z))
    weights = weights - alpha*np.dot(X_new.T,(p-y_train))

In [50]:
weights

array([-0.10236635,  0.67155076])

In [51]:
X_test.shape

(60,)

In [52]:
ones_1 = np.ones((60,))

In [53]:
ones_1.shape

(60,)

In [54]:
X_pred = np.c_[ones_1,X_test]

In [55]:
X_pred.shape

(60, 2)

In [56]:
y_pred = np.dot(X_pred,weights)

In [57]:
y_pred.shape

(60,)

In [58]:
y_pred1 = []
for i in y_pred:
    if i < 0.5:
        y_pred1.append(0)
    else:
        y_pred1.append(1)

In [59]:
le = preprocessing.LabelEncoder()
y_test = le.fit_transform(y_test)
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [60]:
y_pred1

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [61]:
tp, tn = 0,0
for i in range(len(y_pred1)):
    if y_test[i] == 1 and y_pred1[i] == 1:
        tp += 1
    elif y_test[i] == 0 and y_pred1[i] == 0:
        tn += 1
accuracy = (tp+tn)/len(y_pred1)

In [62]:
accuracy

0.6