In [1]:
import numpy as np
import pandas as pd

In [33]:
df = pd.read_csv('Heart.csv')

In [34]:
df = df.dropna()

In [35]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['ChestPain'] = label_encoder.fit_transform(df['ChestPain'])
df['Thal'] = label_encoder.fit_transform(df['Thal'])
df['AHD'] = label_encoder.fit_transform(df['AHD'])

In [36]:
df

Unnamed: 0  Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1          3     145   233    1        2    150   
1             2   67    1          0     160   286    0        2    108   
2             3   67    1          0     120   229    0        2    129   
3             4   37    1          1     130   250    0        0    187   
4             5   41    0          2     130   204    0        2    172   
..          ...  ...  ...        ...     ...   ...  ...      ...    ...   
297         298   57    0          0     140   241    0        0    123   
298         299   45    1          3     110   264    0        0    132   
299         300   68    1          0     144   193    1        0    141   
300         301   57    1          0     130   131    0        0    115   
301         302   57    0          2     130   236    0        2    174   

     ExAng  Oldpeak  Slope   Ca  Thal  AHD  
0        0      2.3      3  0.0     0    0  
1        1      1.5      2  3.0     1    1  
2        1      2.6      2  2.0     2    1  
3        0      3.5      3  0.0     1    0  
4        0      1.4      1  0.0     1    0  
..     ...      ...    ...  ...   ...  ...  
297      1      0.2      2  0.0     2    1  
298      0      1.2      2  0.0     2    1  
299      0      3.4      2  2.0     2    1  
300      1      1.2      2  1.0     2    1  
301      0      0.0      2  1.0     1    1  

[297 rows x 15 columns]

In [37]:
new_df = df.iloc[:,1:14]
new_df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  
0        3  0.0     0  
1        2  3.0     1  
2        2  2.0     2  
3        3  0.0     1  
4        1  0.0     1  
..     ...  ...   ...  
297      2  0.0     2  
298      2  0.0     2  
299      2  2.0     2  
300      2  1.0     2  
301      2  1.0     1  

[297 rows x 13 columns]

In [38]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [94]:
scalar.fit(new_df)
scaled_data = scalar.transform(new_df)
scaled_data.shape

(297, 10)

In [40]:
from sklearn.decomposition import PCA

In [54]:
pca = PCA(n_components=9)
pca.fit(scaled_data)
pcaed_data = pca.transform(scaled_data)

In [55]:
pcaed_data

array([[ 4.26305878e-01,  2.07054232e+00,  3.41183554e+00, ...,
         3.24824955e-01,  6.47810645e-01, -1.43532127e+00],
       [ 3.54620609e+00,  1.00593776e+00, -3.55819376e-01, ...,
        -4.74948837e-01, -1.15784901e+00,  2.93234403e-01],
       [ 3.06060907e+00, -9.03070136e-01, -1.62650476e-01, ...,
        -8.99569616e-01, -1.25298021e-01,  2.70299053e-02],
       ...,
       [ 2.48090336e+00,  3.03568278e-01,  2.23195750e+00, ...,
        -2.96567573e-03,  1.08815823e+00,  8.52382306e-01],
       [ 1.69225564e+00, -2.45975751e+00,  4.14031821e-01, ...,
         3.64540510e-01, -1.18237282e+00,  2.86185578e-01],
       [-1.11876129e+00,  1.43241127e+00, -8.40620398e-02, ...,
        -7.35785843e-01,  2.10108131e-01,  3.77374280e-01]])

In [56]:
pcaed_data.shape

(297, 9)

In [57]:
pca.explained_variance_ratio_

array([0.222684  , 0.12077868, 0.09235659, 0.08754308, 0.07847809,
       0.07196598, 0.06575383, 0.06016464, 0.0526615 ])

In [58]:
exp_var_pca = pca.explained_variance_ratio_

In [59]:
cum_sum_eigenvalues = np.cumsum(exp_var_pca)

In [60]:
cum_sum_eigenvalues

array([0.222684  , 0.34346268, 0.43581927, 0.52336235, 0.60184044,
       0.67380641, 0.73956025, 0.79972489, 0.85238639])

In [61]:
y = df['AHD']

In [62]:
y

0      0
1      1
2      1
3      0
4      0
      ..
297    1
298    1
299    1
300    1
301    1
Name: AHD, Length: 297, dtype: int32

In [63]:
y.shape

(297,)

In [64]:
Processing_data = np.c_[pcaed_data,y]

In [65]:
Processing_data

array([[ 0.42630588,  2.07054232,  3.41183554, ...,  0.64781065,
        -1.43532127,  0.        ],
       [ 3.54620609,  1.00593776, -0.35581938, ..., -1.15784901,
         0.2932344 ,  1.        ],
       [ 3.06060907, -0.90307014, -0.16265048, ..., -0.12529802,
         0.02702991,  1.        ],
       ...,
       [ 2.48090336,  0.30356828,  2.2319575 , ...,  1.08815823,
         0.85238231,  1.        ],
       [ 1.69225564, -2.45975751,  0.41403182, ..., -1.18237282,
         0.28618558,  1.        ],
       [-1.11876129,  1.43241127, -0.08406204, ...,  0.21010813,
         0.37737428,  1.        ]])

In [66]:
new_df = pd.DataFrame(Processing_data, columns = ['PC1','PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9','Target'])

In [67]:
new_df

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0    0.426306  2.070542  3.411836  2.392847  0.179616  1.086600  0.324825   
1    3.546206  1.005938 -0.355819 -0.500573  0.637922  0.873599 -0.474949   
2    3.060609 -0.903070 -0.162650 -0.645419  0.157377  0.648989 -0.899570   
3   -0.387984 -1.439228  1.339869  2.048719 -1.723899 -0.739636 -0.307551   
4   -2.138767  0.372616  0.159760  1.027621 -0.901651  0.609367 -0.065662   
..        ...       ...       ...       ...       ...       ...       ...   
292  1.014478 -0.625628 -1.506455  0.475206  0.174707 -1.423419  1.447769   
293 -0.946766 -1.293388  0.819646  0.443107 -0.655527 -1.087668 -1.170214   
294  2.480903  0.303568  2.231958 -0.737502  1.586505 -1.437693 -0.002966   
295  1.692256 -2.459758  0.414032  0.012629  1.294873 -0.676726  0.364541   
296 -1.118761  1.432411 -0.084062  0.923931 -0.274902  0.566157 -0.735786   

          PC8       PC9  Target  
0    0.647811 -1.435321     0.0  
1   -1.157849  0.293234     1.0  
2   -0.125298  0.027030     1.0  
3    1.912581  0.729419     0.0  
4    0.152871  1.055593     0.0  
..        ...       ...     ...  
292 -0.804965 -0.257981     1.0  
293  0.754982 -2.025356     1.0  
294  1.088158  0.852382     1.0  
295 -1.182373  0.286186     1.0  
296  0.210108  0.377374     1.0  

[297 rows x 10 columns]

In [70]:
new_df_no = new_df[new_df['Target']==0.0]

In [71]:
new_df_no

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0    0.426306  2.070542  3.411836  2.392847  0.179616  1.086600  0.324825   
3   -0.387984 -1.439228  1.339869  2.048719 -1.723899 -0.739636 -0.307551   
4   -2.138767  0.372616  0.159760  1.027621 -0.901651  0.609367 -0.065662   
5   -2.124584 -0.224399  0.484409 -0.136336  0.186538 -0.487277 -0.778647   
7   -0.468955  0.440931 -2.829385 -0.222605 -0.190556 -0.590572  1.248101   
..        ...       ...       ...       ...       ...       ...       ...   
279 -3.138400 -1.377791  0.862540 -0.009008 -0.053563 -0.088589 -0.017748   
283 -1.377166  0.030234  0.710425 -1.043889 -0.889257  0.297557 -0.828279   
284 -1.069953 -0.482014  0.914021  1.399347 -0.103825 -0.452851 -0.703078   
286 -1.632983  1.529187 -1.213692  0.481200 -0.547072 -1.305870 -0.284475   
290 -3.166465 -1.387191  1.121793  0.032988  0.329628 -0.098074 -0.196384   

          PC8       PC9  Target  
0    0.647811 -1.435321     0.0  
3    1.912581  0.729419     0.0  
4    0.152871  1.055593     0.0  
5   -0.178676 -0.570735     0.0  
7    0.432518 -0.681042     0.0  
..        ...       ...     ...  
279  0.015684  0.221210     0.0  
283 -1.026103 -0.448676     0.0  
284  0.443091 -1.212885     0.0  
286  0.559260 -0.724114     0.0  
290 -0.273859  0.421364     0.0  

[160 rows x 10 columns]

In [72]:
new_df_yes = new_df[new_df['Target']==1.0]

In [73]:
new_df_yes

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
1    3.546206  1.005938 -0.355819 -0.500573  0.637922  0.873599 -0.474949   
2    3.060609 -0.903070 -0.162650 -0.645419  0.157377  0.648989 -0.899570   
6    2.285974  1.304149 -0.242576  1.926843 -0.530022  0.190342 -1.172609   
8    1.259169 -0.067042  0.007971 -0.596846 -0.536407  0.350456 -1.095477   
9    2.542505 -0.781660  2.263874  0.435112 -1.107667  0.346805  2.083430   
..        ...       ...       ...       ...       ...       ...       ...   
292  1.014478 -0.625628 -1.506455  0.475206  0.174707 -1.423419  1.447769   
293 -0.946766 -1.293388  0.819646  0.443107 -0.655527 -1.087668 -1.170214   
294  2.480903  0.303568  2.231958 -0.737502  1.586505 -1.437693 -0.002966   
295  1.692256 -2.459758  0.414032  0.012629  1.294873 -0.676726  0.364541   
296 -1.118761  1.432411 -0.084062  0.923931 -0.274902  0.566157 -0.735786   

          PC8       PC9  Target  
1   -1.157849  0.293234     1.0  
2   -0.125298  0.027030     1.0  
6    1.449003  1.677856     1.0  
8   -0.083933  0.214654     1.0  
9    1.088861  0.162669     1.0  
..        ...       ...     ...  
292 -0.804965 -0.257981     1.0  
293  0.754982 -2.025356     1.0  
294  1.088158  0.852382     1.0  
295 -1.182373  0.286186     1.0  
296  0.210108  0.377374     1.0  

[137 rows x 10 columns]

In [77]:
new_df_1 = new_df_no.iloc[:,:9]
new_df_1

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0    0.426306  2.070542  3.411836  2.392847  0.179616  1.086600  0.324825   
3   -0.387984 -1.439228  1.339869  2.048719 -1.723899 -0.739636 -0.307551   
4   -2.138767  0.372616  0.159760  1.027621 -0.901651  0.609367 -0.065662   
5   -2.124584 -0.224399  0.484409 -0.136336  0.186538 -0.487277 -0.778647   
7   -0.468955  0.440931 -2.829385 -0.222605 -0.190556 -0.590572  1.248101   
..        ...       ...       ...       ...       ...       ...       ...   
279 -3.138400 -1.377791  0.862540 -0.009008 -0.053563 -0.088589 -0.017748   
283 -1.377166  0.030234  0.710425 -1.043889 -0.889257  0.297557 -0.828279   
284 -1.069953 -0.482014  0.914021  1.399347 -0.103825 -0.452851 -0.703078   
286 -1.632983  1.529187 -1.213692  0.481200 -0.547072 -1.305870 -0.284475   
290 -3.166465 -1.387191  1.121793  0.032988  0.329628 -0.098074 -0.196384   

          PC8       PC9  
0    0.647811 -1.435321  
3    1.912581  0.729419  
4    0.152871  1.055593  
5   -0.178676 -0.570735  
7    0.432518 -0.681042  
..        ...       ...  
279  0.015684  0.221210  
283 -1.026103 -0.448676  
284  0.443091 -1.212885  
286  0.559260 -0.724114  
290 -0.273859  0.421364  

[160 rows x 9 columns]

In [86]:
mean_values_no = new_df_1.mean()
mean_values_no

PC1   -1.032468
PC2    0.194537
PC3   -0.014964
PC4    0.187218
PC5    0.033655
PC6   -0.024067
PC7    0.056062
PC8    0.010079
PC9   -0.064425
dtype: float64

In [79]:
new_df_2 = new_df_yes.iloc[:,:9]

In [80]:
new_df_2

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
1    3.546206  1.005938 -0.355819 -0.500573  0.637922  0.873599 -0.474949   
2    3.060609 -0.903070 -0.162650 -0.645419  0.157377  0.648989 -0.899570   
6    2.285974  1.304149 -0.242576  1.926843 -0.530022  0.190342 -1.172609   
8    1.259169 -0.067042  0.007971 -0.596846 -0.536407  0.350456 -1.095477   
9    2.542505 -0.781660  2.263874  0.435112 -1.107667  0.346805  2.083430   
..        ...       ...       ...       ...       ...       ...       ...   
292  1.014478 -0.625628 -1.506455  0.475206  0.174707 -1.423419  1.447769   
293 -0.946766 -1.293388  0.819646  0.443107 -0.655527 -1.087668 -1.170214   
294  2.480903  0.303568  2.231958 -0.737502  1.586505 -1.437693 -0.002966   
295  1.692256 -2.459758  0.414032  0.012629  1.294873 -0.676726  0.364541   
296 -1.118761  1.432411 -0.084062  0.923931 -0.274902  0.566157 -0.735786   

          PC8       PC9  
1   -1.157849  0.293234  
2   -0.125298  0.027030  
6    1.449003  1.677856  
8   -0.083933  0.214654  
9    1.088861  0.162669  
..        ...       ...  
292 -0.804965 -0.257981  
293  0.754982 -2.025356  
294  1.088158  0.852382  
295 -1.182373  0.286186  
296  0.210108  0.377374  

[137 rows x 9 columns]

In [87]:
mean_values_yes = new_df_2.mean()

In [81]:
cov_new_df1 = new_df_1.cov()

In [82]:
cov_new_df2 = new_df_2.cov()
cov_new_df2

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
PC1  2.075270  0.060795  0.007711  0.299571  0.007571 -0.080854  0.167949   
PC2  0.060795  1.667996  0.155998 -0.092542  0.041569  0.085907 -0.008230   
PC3  0.007711  0.155998  0.938913  0.119166  0.048356 -0.035829 -0.041757   
PC4  0.299571 -0.092542  0.119166  1.161833  0.029012 -0.028603  0.070003   
PC5  0.007571  0.041569  0.048356  0.029012  1.098811  0.207034 -0.092221   
PC6 -0.080854  0.085907 -0.035829 -0.028603  0.207034  1.083777 -0.058319   
PC7  0.167949 -0.008230 -0.041757  0.070003 -0.092221 -0.058319  1.162158   
PC8  0.187682  0.040734  0.050163 -0.015457  0.021843 -0.013786 -0.067666   
PC9  0.137518  0.202794  0.093347 -0.038720 -0.015492 -0.009373 -0.088618   

          PC8       PC9  
PC1  0.187682  0.137518  
PC2  0.040734  0.202794  
PC3  0.050163  0.093347  
PC4 -0.015457 -0.038720  
PC5  0.021843 -0.015492  
PC6 -0.013786 -0.009373  
PC7 -0.067666 -0.088618  
PC8  0.847344  0.050569  
PC9  0.050569  0.759091

In [83]:
Sw = 160*cov_new_df1 + 137*cov_new_df2
Sw

PC1         PC2         PC3         PC4         PC5         PC6  \
PC1  493.414351   70.115263   -5.391432   67.512156   12.129363   -8.684766   
PC2   70.115263  456.291205    1.038628  -12.725839   -2.279191    1.646604   
PC3   -5.391432    1.038628  358.889156    0.995072    0.182771   -0.130883   
PC4   67.512156  -12.725839    0.995072  328.063549   -2.195030    1.568556   
PC5   12.129363   -2.279191    0.182771   -2.195030  304.673194    0.312657   
PC6   -8.684766    1.646604   -0.130883    1.568556    0.312657  279.562787   
PC7   20.227797   -3.807927    0.286772   -3.653388   -0.671897    0.462506   
PC8    3.659536   -0.678521    0.059901   -0.660899   -0.115242    0.082676   
PC9  -23.197391    4.403927   -0.322988    4.204404    0.754554   -0.542549   

            PC7         PC8         PC9  
PC1   20.227797    3.659536  -23.197391  
PC2   -3.807927   -0.678521    4.403927  
PC3    0.286772    0.059901   -0.322988  
PC4   -3.653388   -0.660899    4.204404  
PC5   -0.671897   -0.115242    0.754554  
PC6    0.462506    0.082676   -0.542549  
PC7  254.543323   -0.207024    1.247865  
PC8   -0.207024  233.843781    0.233973  
PC9    1.247865    0.233973  203.265883

In [84]:
# Sw inverse calc
Sw = np.linalg.inv(Sw)
Sw.shape

(9, 9)

In [88]:
mean_diff = mean_values_yes - mean_values_no

In [89]:
mean_diff

PC1    2.238270
PC2   -0.421734
PC3    0.032440
PC4   -0.405867
PC5   -0.072959
PC6    0.052174
PC7   -0.121537
PC8   -0.021851
PC9    0.139666
dtype: float64

In [90]:
mean_diff.shape

(9,)

In [91]:
W = np.dot(Sw,mean_diff)

In [95]:
W.shape

(9,)

In [96]:
pcaed_data

array([[ 4.26305878e-01,  2.07054232e+00,  3.41183554e+00, ...,
         3.24824955e-01,  6.47810645e-01, -1.43532127e+00],
       [ 3.54620609e+00,  1.00593776e+00, -3.55819376e-01, ...,
        -4.74948837e-01, -1.15784901e+00,  2.93234403e-01],
       [ 3.06060907e+00, -9.03070136e-01, -1.62650476e-01, ...,
        -8.99569616e-01, -1.25298021e-01,  2.70299053e-02],
       ...,
       [ 2.48090336e+00,  3.03568278e-01,  2.23195750e+00, ...,
        -2.96567573e-03,  1.08815823e+00,  8.52382306e-01],
       [ 1.69225564e+00, -2.45975751e+00,  4.14031821e-01, ...,
         3.64540510e-01, -1.18237282e+00,  2.86185578e-01],
       [-1.11876129e+00,  1.43241127e+00, -8.40620398e-02, ...,
        -7.35785843e-01,  2.10108131e-01,  3.77374280e-01]])

In [97]:
pcaed_data.shape

(297, 9)

In [98]:
projections = np.dot(pcaed_data,W)

In [99]:
projections

array([-8.81322588e-03,  1.90509367e-02,  2.03634265e-02, -2.63022758e-03,
       -1.22124505e-02, -1.06135676e-02,  8.42732493e-03, -5.61241914e-03,
        9.95157819e-03,  1.28212299e-02, -6.88608071e-03, -8.78145194e-03,
       -1.27225371e-03, -8.23094811e-03, -2.83061023e-03, -5.02920642e-03,
       -3.60222855e-03, -3.05530588e-03, -1.18407230e-02, -1.09919745e-02,
       -1.49369874e-03, -1.45227403e-02, -4.13767183e-03,  1.06677898e-02,
        1.95889277e-02, -9.15947945e-03, -1.37187846e-02, -6.74399372e-03,
       -3.84657439e-03,  1.13773393e-02, -6.48432482e-03,  1.07691727e-02,
       -7.22637911e-03,  1.81757709e-03, -5.49601244e-03, -7.26554215e-03,
        1.24682009e-02,  5.08433253e-03,  1.09822008e-02, -6.21937404e-05,
        1.37325105e-02, -4.28302722e-03, -6.36311040e-03, -5.34254139e-03,
       -7.80881845e-03,  7.29583092e-03, -5.67278686e-03,  9.54678404e-03,
       -6.19317550e-03, -2.04391887e-03, -1.45403560e-02,  1.91968124e-03,
       -1.13876771e-03, -

In [100]:
X = projections

In [101]:
X.shape

(297,)

In [102]:
y.shape

(297,)

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 22)

In [105]:
weights = np.zeros((2,))

In [106]:
ones = np.ones((237,))

In [107]:
X_new = np.c_[ones,X_train]

In [108]:
X_new.shape

(237, 2)

In [109]:
iter = 800

In [110]:
alpha = 0.001

In [111]:
from numpy import exp
for i in range(iter):
    z = np.dot(X_new,weights)
    p = 1/(1+exp(-z))
    weights = weights - alpha*np.dot(X_new.T,(p-y_train))

In [112]:
weights

array([-0.09319673,  0.64458305])

In [113]:
ones_1 = np.ones((60,))

In [114]:
X_pred = np.c_[ones_1,X_test]

In [115]:
X_pred

array([[ 1.00000000e+00, -1.50534303e-02],
       [ 1.00000000e+00, -1.36905960e-02],
       [ 1.00000000e+00, -4.42621498e-03],
       [ 1.00000000e+00, -1.37187846e-02],
       [ 1.00000000e+00,  6.46043449e-03],
       [ 1.00000000e+00, -7.48817757e-03],
       [ 1.00000000e+00, -9.96679622e-03],
       [ 1.00000000e+00, -5.02920642e-03],
       [ 1.00000000e+00,  2.18607242e-03],
       [ 1.00000000e+00, -6.33284743e-04],
       [ 1.00000000e+00,  8.05853678e-03],
       [ 1.00000000e+00, -4.06262217e-03],
       [ 1.00000000e+00,  6.41345859e-03],
       [ 1.00000000e+00, -3.71134422e-03],
       [ 1.00000000e+00, -5.21086953e-03],
       [ 1.00000000e+00, -1.95259929e-03],
       [ 1.00000000e+00,  1.24682009e-02],
       [ 1.00000000e+00,  1.67801442e-03],
       [ 1.00000000e+00, -6.51142310e-03],
       [ 1.00000000e+00, -3.84657439e-03],
       [ 1.00000000e+00, -8.60809548e-03],
       [ 1.00000000e+00, -9.81291819e-03],
       [ 1.00000000e+00, -1.60201210e-02],
       [ 1.

In [116]:
X_pred.shape

(60, 2)

In [117]:
y_pred = np.dot(X_pred,weights)

In [118]:
y_pred

array([-0.10289991, -0.10202145, -0.09604979, -0.10203962, -0.08903244,
       -0.09802348, -0.09962115, -0.09643847, -0.09178762, -0.09360493,
       -0.08800233, -0.09581542, -0.08906272, -0.095589  , -0.09655556,
       -0.09445534, -0.08515994, -0.09211511, -0.09739388, -0.09567616,
       -0.09874536, -0.09952197, -0.10352302, -0.08380381, -0.09875033,
       -0.09551537, -0.09542037, -0.09146748, -0.08864796, -0.08272937,
       -0.08095359, -0.0940168 , -0.0819417 , -0.09913022, -0.0889752 ,
       -0.10013803, -0.09595749, -0.10483785, -0.08322756, -0.10210776,
       -0.08274627, -0.09785473, -0.10256919, -0.09661885, -0.09671007,
       -0.09695271, -0.08471209, -0.09423073, -0.0966847 , -0.08813292,
       -0.09494948, -0.08034611, -0.09415954, -0.10399055, -0.09614809,
       -0.10109419, -0.09976418, -0.08871605, -0.10117559, -0.09664044])

In [119]:
y_pred1 = []
for i in y_pred:
    if i < 0.5:
        y_pred1.append(0)
    else:
        y_pred1.append(1)

In [125]:
y_test = y_test.to_numpy()

In [126]:
tp, tn = 0,0
for i in range(len(y_pred1)):
    if y_test[i] == 1 and y_pred1[i] == 1:
        tp += 1
    elif y_test[i] == 0 and y_pred1[i] == 0:
        tn += 1
accuracy = (tp+tn)/len(y_pred1)

In [127]:
accuracy

0.6