In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('real_estate.csv')

In [4]:
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [5]:
X = df.iloc[:,1:7]

In [6]:
X

X1 transaction date  X2 house age  \
0               2012.917          32.0   
1               2012.917          19.5   
2               2013.583          13.3   
3               2013.500          13.3   
4               2012.833           5.0   
..                   ...           ...   
409             2013.000          13.7   
410             2012.667           5.6   
411             2013.250          18.8   
412             2013.000           8.1   
413             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  
0       24.98298     121.54024  
1       24.98034     121.53951  
2       24.98746     121.54391  
3       24.98746     121.54391  
4       24.97937     121.54245  
..           ...           ...  
409     24.94155     121.50381  
410     24.97433     121.54310  
411     24.97923     121.53986  
412     24.96674     121.54067  
413     24.97433     121.54310  

[414 rows x 6 columns]

In [7]:
y = df.iloc[:,7]

In [8]:
y.shape

(414,)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 22)

In [11]:
X_train.shape

(331, 6)

In [12]:
y_train.shape

(331,)

In [13]:
X_test.shape

(83, 6)

In [14]:
first_trm = np.dot(X_train.T,X_train)

In [15]:
first_trm.shape

(6, 6)

In [16]:
first_trm = np.linalg.inv(first_trm)

In [17]:
first_trm.shape

(6, 6)

In [18]:
second_trm = np.dot(X_train.T,y_train)

In [19]:
second_trm

array([25323263.1961  ,   212091.91    ,  9244035.513678,    59794.7     ,
         314109.398391,  1528783.254987])

In [20]:
second_trm.shape

(6,)

In [21]:
weights = np.dot(first_trm,second_trm)

In [22]:
weights.shape

(6,)

In [23]:
weights

array([ 3.19998990e+00, -2.88642588e-01, -5.59305246e-03,  1.09875854e+00,
        2.19081102e+02, -9.76516497e+01])

In [24]:
y_pred = np.dot(X_test,weights)

In [25]:
y_pred

array([45.43647786, 36.77909421, 13.99797767, 12.91184265, 34.69639438,
       29.78967691, 33.55895436, 32.02164775, 43.29637586, 26.33746509,
       42.93326715, 41.92561859, 42.33782857, 11.98830334, 37.58738909,
       42.30179183, 44.76957058, 36.04112544, 40.83593165, 31.9020911 ,
       42.23883653, 11.98687132,  8.79189112, 38.06395338, 23.28557849,
       29.750278  , 48.07996147, 32.6115736 , 45.21417613, 30.12628753,
       28.06840409, 40.68315656, 39.00966931, 29.28919899, 42.21161903,
       35.50542428, 28.92560882, 13.38851245, 50.77122811, 34.81826055,
       50.80009237, 27.67914612, 46.62032304, 13.0441972 , 30.24253858,
       35.66980293, 28.01198606, 30.92621316, 46.87858904, 39.47173804,
       13.78448356, 48.3779143 , 31.47967684, 43.9325198 , 48.02181307,
       53.20590563, 34.22207314, 31.63251302, 51.33855174, 44.34088274,
       44.30957186, 44.45555967, 41.20527619, 46.83493856, 42.08373467,
       47.64769755, 44.18993643, 31.71641175, 44.94589487, 42.77

In [26]:
y_pred.shape

(83,)

In [27]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

90.76763522383457

In [28]:
rss = y_test - y_pred

In [29]:
rss.shape

(83,)

In [30]:
rss

46     -3.436478
267     4.320906
40      1.902022
384    -0.011843
71      6.103606
         ...    
119    13.166885
98      4.774756
73      5.525353
406    -9.165700
89     10.154819
Name: Y house price of unit area, Length: 83, dtype: float64

In [31]:
mse = np.dot(rss.T,rss)/rss.shape

In [32]:
mse

array([90.76763522])

In [33]:
rmse = np.sqrt(mse)

In [34]:
rmse

array([9.52720501])

In [35]:
y_mean = y_test.mean()

In [36]:
y_mean

37.89156626506024

In [37]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5119711107180154