In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [111]:
df = pd.read_csv('iris.csv')

In [112]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [113]:
df.isnull().sum().sum()

0

In [114]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [115]:
df = df.iloc[:,1:]

In [116]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [117]:
mean_iris_setosa = df.groupby('Species').mean().loc['Iris-setosa']

In [118]:
mean_iris_setosa

SepalLengthCm    5.006
SepalWidthCm     3.418
PetalLengthCm    1.464
PetalWidthCm     0.244
Name: Iris-setosa, dtype: float64

In [119]:
mean_Iris_versicolor = df.groupby('Species').mean().loc['Iris-versicolor']

In [120]:
mean_Iris_versicolor

SepalLengthCm    5.936
SepalWidthCm     2.770
PetalLengthCm    4.260
PetalWidthCm     1.326
Name: Iris-versicolor, dtype: float64

In [121]:
mean_Iris_virginica = df.groupby('Species').mean().loc['Iris-virginica']

In [122]:
mean_Iris_virginica

SepalLengthCm    6.588
SepalWidthCm     2.974
PetalLengthCm    5.552
PetalWidthCm     2.026
Name: Iris-virginica, dtype: float64

In [123]:
new_df = df.iloc[:,0:4]

In [124]:
new_df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [125]:
new_df_setosa = df[df['Species']=='Iris-setosa']

In [126]:
new_df_setosa

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0             5.1           3.5            1.4           0.2  Iris-setosa
1             4.9           3.0            1.4           0.2  Iris-setosa
2             4.7           3.2            1.3           0.2  Iris-setosa
3             4.6           3.1            1.5           0.2  Iris-setosa
4             5.0           3.6            1.4           0.2  Iris-setosa
5             5.4           3.9            1.7           0.4  Iris-setosa
6             4.6           3.4            1.4           0.3  Iris-setosa
7             5.0           3.4            1.5           0.2  Iris-setosa
8             4.4           2.9            1.4           0.2  Iris-setosa
9             4.9           3.1            1.5           0.1  Iris-setosa
10            5.4           3.7            1.5           0.2  Iris-setosa
11            4.8           3.4            1.6           0.2  Iris-setosa
12            4.8           3.0            1.4           0.1  Iris-setosa
13            4.3           3.0            1.1           0.1  Iris-setosa
14            5.8           4.0            1.2           0.2  Iris-setosa
15            5.7           4.4            1.5           0.4  Iris-setosa
16            5.4           3.9            1.3           0.4  Iris-setosa
17            5.1           3.5            1.4           0.3  Iris-setosa
18            5.7           3.8            1.7           0.3  Iris-setosa
19            5.1           3.8            1.5           0.3  Iris-setosa
20            5.4           3.4            1.7           0.2  Iris-setosa
21            5.1           3.7            1.5           0.4  Iris-setosa
22            4.6           3.6            1.0           0.2  Iris-setosa
23            5.1           3.3            1.7           0.5  Iris-setosa
24            4.8           3.4            1.9           0.2  Iris-setosa
25            5.0           3.0            1.6           0.2  Iris-setosa
26            5.0           3.4            1.6           0.4  Iris-setosa
27            5.2           3.5            1.5           0.2  Iris-setosa
28            5.2           3.4            1.4           0.2  Iris-setosa
29            4.7           3.2            1.6           0.2  Iris-setosa
30            4.8           3.1            1.6           0.2  Iris-setosa
31            5.4           3.4            1.5           0.4  Iris-setosa
32            5.2           4.1            1.5           0.1  Iris-setosa
33            5.5           4.2            1.4           0.2  Iris-setosa
34            4.9           3.1            1.5           0.1  Iris-setosa
35            5.0           3.2            1.2           0.2  Iris-setosa
36            5.5           3.5            1.3           0.2  Iris-setosa
37            4.9           3.1            1.5           0.1  Iris-setosa
38            4.4           3.0            1.3           0.2  Iris-setosa
39            5.1           3.4            1.5           0.2  Iris-setosa
40            5.0           3.5            1.3           0.3  Iris-setosa
41            4.5           2.3            1.3           0.3  Iris-setosa
42            4.4           3.2            1.3           0.2  Iris-setosa
43            5.0           3.5            1.6           0.6  Iris-setosa
44            5.1           3.8            1.9           0.4  Iris-setosa
45            4.8           3.0            1.4           0.3  Iris-setosa
46            5.1           3.8            1.6           0.2  Iris-setosa
47            4.6           3.2            1.4           0.2  Iris-setosa
48            5.3           3.7            1.5           0.2  Iris-setosa
49            5.0           3.3            1.4           0.2  Iris-setosa

In [127]:
new_df_virginica = df[df['Species']=='Iris-virginica']

In [128]:
new_df_virginica

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
100            6.3           3.3            6.0           2.5  Iris-virginica
101            5.8           2.7            5.1           1.9  Iris-virginica
102            7.1           3.0            5.9           2.1  Iris-virginica
103            6.3           2.9            5.6           1.8  Iris-virginica
104            6.5           3.0            5.8           2.2  Iris-virginica
105            7.6           3.0            6.6           2.1  Iris-virginica
106            4.9           2.5            4.5           1.7  Iris-virginica
107            7.3           2.9            6.3           1.8  Iris-virginica
108            6.7           2.5            5.8           1.8  Iris-virginica
109            7.2           3.6            6.1           2.5  Iris-virginica
110            6.5           3.2            5.1           2.0  Iris-virginica
111            6.4           2.7            5.3           1.9  Iris-virginica
112            6.8           3.0            5.5           2.1  Iris-virginica
113            5.7           2.5            5.0           2.0  Iris-virginica
114            5.8           2.8            5.1           2.4  Iris-virginica
115            6.4           3.2            5.3           2.3  Iris-virginica
116            6.5           3.0            5.5           1.8  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
118            7.7           2.6            6.9           2.3  Iris-virginica
119            6.0           2.2            5.0           1.5  Iris-virginica
120            6.9           3.2            5.7           2.3  Iris-virginica
121            5.6           2.8            4.9           2.0  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
123            6.3           2.7            4.9           1.8  Iris-virginica
124            6.7           3.3            5.7           2.1  Iris-virginica
125            7.2           3.2            6.0           1.8  Iris-virginica
126            6.2           2.8            4.8           1.8  Iris-virginica
127            6.1           3.0            4.9           1.8  Iris-virginica
128            6.4           2.8            5.6           2.1  Iris-virginica
129            7.2           3.0            5.8           1.6  Iris-virginica
130            7.4           2.8            6.1           1.9  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica
132            6.4           2.8            5.6           2.2  Iris-virginica
133            6.3           2.8            5.1           1.5  Iris-virginica
134            6.1           2.6            5.6           1.4  Iris-virginica
135            7.7           3.0            6.1           2.3  Iris-virginica
136            6.3           3.4            5.6           2.4  Iris-virginica
137            6.4           3.1            5.5           1.8  Iris-virginica
138            6.0           3.0            4.8           1.8  Iris-virginica
139            6.9           3.1            5.4           2.1  Iris-virginica
140            6.7           3.1            5.6           2.4  Iris-virginica
141            6.9           3.1            5.1           2.3  Iris-virginica
142            5.8           2.7            5.1           1.9  Iris-virginica
143            6.8           3.2            5.9           2.3  Iris-virginica
144            6.7           3.3            5.7           2.5  Iris-virginica
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

In [129]:
new_df_versicolor = df[df['Species']=='Iris-versicolor']

In [130]:
new_df_versicolor

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor
55            5.7           2.8            4.5           1.3  Iris-versicolor
56            6.3           3.3            4.7           1.6  Iris-versicolor
57            4.9           2.4            3.3           1.0  Iris-versicolor
58            6.6           2.9            4.6           1.3  Iris-versicolor
59            5.2           2.7            3.9           1.4  Iris-versicolor
60            5.0           2.0            3.5           1.0  Iris-versicolor
61            5.9           3.0            4.2           1.5  Iris-versicolor
62            6.0           2.2            4.0           1.0  Iris-versicolor
63            6.1           2.9            4.7           1.4  Iris-versicolor
64            5.6           2.9            3.6           1.3  Iris-versicolor
65            6.7           3.1            4.4           1.4  Iris-versicolor
66            5.6           3.0            4.5           1.5  Iris-versicolor
67            5.8           2.7            4.1           1.0  Iris-versicolor
68            6.2           2.2            4.5           1.5  Iris-versicolor
69            5.6           2.5            3.9           1.1  Iris-versicolor
70            5.9           3.2            4.8           1.8  Iris-versicolor
71            6.1           2.8            4.0           1.3  Iris-versicolor
72            6.3           2.5            4.9           1.5  Iris-versicolor
73            6.1           2.8            4.7           1.2  Iris-versicolor
74            6.4           2.9            4.3           1.3  Iris-versicolor
75            6.6           3.0            4.4           1.4  Iris-versicolor
76            6.8           2.8            4.8           1.4  Iris-versicolor
77            6.7           3.0            5.0           1.7  Iris-versicolor
78            6.0           2.9            4.5           1.5  Iris-versicolor
79            5.7           2.6            3.5           1.0  Iris-versicolor
80            5.5           2.4            3.8           1.1  Iris-versicolor
81            5.5           2.4            3.7           1.0  Iris-versicolor
82            5.8           2.7            3.9           1.2  Iris-versicolor
83            6.0           2.7            5.1           1.6  Iris-versicolor
84            5.4           3.0            4.5           1.5  Iris-versicolor
85            6.0           3.4            4.5           1.6  Iris-versicolor
86            6.7           3.1            4.7           1.5  Iris-versicolor
87            6.3           2.3            4.4           1.3  Iris-versicolor
88            5.6           3.0            4.1           1.3  Iris-versicolor
89            5.5           2.5            4.0           1.3  Iris-versicolor
90            5.5           2.6            4.4           1.2  Iris-versicolor
91            6.1           3.0            4.6           1.4  Iris-versicolor
92            5.8           2.6            4.0           1.2  Iris-versicolor
93            5.0           2.3            3.3           1.0  Iris-versicolor
94            5.6           2.7            4.2           1.3  Iris-versicolor
95            5.7           3.0            4.2           1.2  Iris-versicolor
96            5.7           2.9            4.2           1.3  Iris-versicolor
97            6.2           2.9            4.3           1.3  Iris-versicolor
98            5.1           2.5            3.0           1.1  Iris-versicolor
99            5.7           2.8            4.1           1.3  Iris-versicolor

In [131]:
cov_setosa = new_df_setosa.cov()
cov_virginica = new_df_virginica.cov()
cov_versicolor = new_df_versicolor.cov()

In [132]:
cov_setosa

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.124249      0.100298       0.016139      0.010547
SepalWidthCm        0.100298      0.145180       0.011682      0.011437
PetalLengthCm       0.016139      0.011682       0.030106      0.005698
PetalWidthCm        0.010547      0.011437       0.005698      0.011494

In [133]:
Sw = cov_setosa + cov_versicolor + cov_virginica

In [134]:
Sw

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.795024      0.279245       0.502327      0.115420
SepalWidthCm        0.279245      0.347653       0.165714      0.100269
PetalLengthCm       0.502327      0.165714       0.555510      0.127624
PetalWidthCm        0.115420      0.100269       0.127624      0.126033

In [135]:
mean_data = df.mean()

C:\Users\SDCBSDELHI\AppData\Local\Temp\ipykernel_3896\2454205763.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean_data = df.mean()


In [136]:
mean_data

SepalLengthCm    5.843333
SepalWidthCm     3.054000
PetalLengthCm    3.758667
PetalWidthCm     1.198667
dtype: float64

In [137]:
df['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [138]:
sb_setosa = mean_iris_setosa - mean_data

In [139]:
sb_setosa 

SepalLengthCm   -0.837333
SepalWidthCm     0.364000
PetalLengthCm   -2.294667
PetalWidthCm    -0.954667
dtype: float64

In [140]:
s = np.matrix(sb_setosa)

In [141]:
a = s.T

In [142]:
sb1 = a@s 

In [143]:
sb1 = 50*sb1

In [144]:
sb1

matrix([[ 35.05635556, -15.23946667,  96.07004444,  39.96871111],
        [-15.23946667,   6.6248    , -41.76293333, -17.37493333],
        [ 96.07004444, -41.76293333, 263.27475556, 109.53208889],
        [ 39.96871111, -17.37493333, 109.53208889,  45.56942222]])

In [145]:
sb_virginica = mean_Iris_virginica - mean_data

In [146]:
s1 = np.matrix(sb_virginica)

In [147]:
b = s1.T

In [148]:
sb2 = b@s1

In [149]:
sb2

matrix([[ 0.55452844, -0.05957333,  1.33543556,  0.61608756],
        [-0.05957333,  0.0064    , -0.14346667, -0.06618667],
        [ 1.33543556, -0.14346667,  3.21604444,  1.48368444],
        [ 0.61608756, -0.06618667,  1.48368444,  0.68448044]])

In [150]:
sb2 = 50*sb2

In [151]:
sb2

matrix([[ 27.72642222,  -2.97866667,  66.77177778,  30.80437778],
        [ -2.97866667,   0.32      ,  -7.17333333,  -3.30933333],
        [ 66.77177778,  -7.17333333, 160.80222222,  74.18422222],
        [ 30.80437778,  -3.30933333,  74.18422222,  34.22402222]])

In [152]:
sb_versicolor = mean_Iris_versicolor - mean_data

In [153]:
s2 = np.matrix(sb_versicolor)

In [154]:
c = s2.T

In [155]:
sb3 = c@s2

In [156]:
sb3 = 50*sb3

In [157]:
sb3

matrix([[ 0.42935556, -1.31586667,  2.32284444,  0.58997778],
        [-1.31586667,  4.0328    , -7.11893333, -1.80813333],
        [ 2.32284444, -7.11893333, 12.56675556,  3.19182222],
        [ 0.58997778, -1.80813333,  3.19182222,  0.81068889]])

In [158]:
Sb = sb1 + sb2 + sb3

In [159]:
Sb

matrix([[ 63.21213333, -19.534     , 165.16466667,  71.36306667],
        [-19.534     ,  10.9776    , -56.0552    , -22.4924    ],
        [165.16466667, -56.0552    , 436.64373333, 186.90813333],
        [ 71.36306667, -22.4924    , 186.90813333,  80.60413333]])

In [160]:
Sb.shape

(4, 4)

In [161]:
Sw.shape

(4, 4)

In [162]:
Sw1 = np.linalg.inv(Sw)

In [163]:
Sw1

array([[ 3.62374533, -1.81576752, -3.00331261,  1.1672211 ],
       [-1.81576752,  4.78253255,  0.921823  , -3.07549007],
       [-3.00331261,  0.921823  ,  4.92280023, -2.96793664],
       [ 1.1672211 , -3.07549007, -2.96793664, 12.31774253]])

In [164]:
Decom_mat = np.dot(Sw1,Sb)

In [165]:
Decom_mat

matrix([[-148.210773  ,   51.37867426, -392.91661175, -167.81815936],
        [-275.42434345,  105.47211217, -740.31232678, -312.7503688 ],
        [ 393.41891155, -140.40642082, 1047.064276  ,  445.82383193],
        [ 522.69277373, -167.24930669, 1371.53622162,  590.60109334]])

In [166]:
eigen_values, eigen_vectors = np.linalg.eig(Decom_mat)

In [167]:
eigen_values

array([1.58132593e+03+0.00000000e+00j, 1.36007763e+01+0.00000000e+00j,
       5.81294993e-14+1.38933945e-13j, 5.81294993e-14-1.38933945e-13j])

In [168]:
eigen_vectors

matrix([[-0.20490976+0.j        , -0.00898234+0.j        ,
          0.29047527-0.27309424j,  0.29047527+0.27309424j],
        [-0.38714331+0.j        , -0.58899857+0.j        ,
         -0.39592951+0.12056657j, -0.39592951-0.12056657j],
        [ 0.54648218+0.j        ,  0.25428655+0.j        ,
         -0.44910723+0.11877853j, -0.44910723-0.11877853j],
        [ 0.71378517+0.j        , -0.76703217+0.j        ,
          0.67375183+0.j        ,  0.67375183-0.j        ]])

In [169]:
eig_pairs = [(np.abs(eigen_values[i]), eigen_vectors[:,i]) for i in range(len(eigen_values))]

In [170]:
eig_pairs

[(1581.3259321867647,
  matrix([[-0.20490976+0.j],
          [-0.38714331+0.j],
          [ 0.54648218+0.j],
          [ 0.71378517+0.j]])),
 (13.600776328162155,
  matrix([[-0.00898234+0.j],
          [-0.58899857+0.j],
          [ 0.25428655+0.j],
          [-0.76703217+0.j]])),
 (1.5060438138576606e-13,
  matrix([[ 0.29047527-0.27309424j],
          [-0.39592951+0.12056657j],
          [-0.44910723+0.11877853j],
          [ 0.67375183+0.j        ]])),
 (1.5060438138576606e-13,
  matrix([[ 0.29047527+0.27309424j],
          [-0.39592951-0.12056657j],
          [-0.44910723-0.11877853j],
          [ 0.67375183-0.j        ]]))]

In [171]:
eig_pairs = sorted(eig_pairs, key=lambda k: k[0], reverse=True)

In [172]:
eig_pairs

[(1581.3259321867647,
  matrix([[-0.20490976+0.j],
          [-0.38714331+0.j],
          [ 0.54648218+0.j],
          [ 0.71378517+0.j]])),
 (13.600776328162155,
  matrix([[-0.00898234+0.j],
          [-0.58899857+0.j],
          [ 0.25428655+0.j],
          [-0.76703217+0.j]])),
 (1.5060438138576606e-13,
  matrix([[ 0.29047527-0.27309424j],
          [-0.39592951+0.12056657j],
          [-0.44910723+0.11877853j],
          [ 0.67375183+0.j        ]])),
 (1.5060438138576606e-13,
  matrix([[ 0.29047527+0.27309424j],
          [-0.39592951-0.12056657j],
          [-0.44910723-0.11877853j],
          [ 0.67375183-0.j        ]]))]

In [173]:
for i in eig_pairs:
    print(i[0])

1581.3259321867647
13.600776328162155
1.5060438138576606e-13
1.5060438138576606e-13


In [174]:
eigv_sum = sum(eigen_values)
for i,j in enumerate(eig_pairs):
    print('eigenvalue {0:}: {1:.2%}'.format(i+1, (j[0]/eigv_sum).real))

eigenvalue 1: 99.15%
eigenvalue 2: 0.85%
eigenvalue 3: 0.00%
eigenvalue 4: 0.00%


In [175]:
eig_pairs

[(1581.3259321867647,
  matrix([[-0.20490976+0.j],
          [-0.38714331+0.j],
          [ 0.54648218+0.j],
          [ 0.71378517+0.j]])),
 (13.600776328162155,
  matrix([[-0.00898234+0.j],
          [-0.58899857+0.j],
          [ 0.25428655+0.j],
          [-0.76703217+0.j]])),
 (1.5060438138576606e-13,
  matrix([[ 0.29047527-0.27309424j],
          [-0.39592951+0.12056657j],
          [-0.44910723+0.11877853j],
          [ 0.67375183+0.j        ]])),
 (1.5060438138576606e-13,
  matrix([[ 0.29047527+0.27309424j],
          [-0.39592951-0.12056657j],
          [-0.44910723-0.11877853j],
          [ 0.67375183-0.j        ]]))]

In [176]:
vecs = np.matrix([[-0.20490976, -0.00898234],[-0.38714331, -0.58899857],[0.54648218, 0.25428655],[0.71378517, -0.76703217]])

In [177]:
vecs
vecs.shape

(4, 2)

In [178]:
W = vecs
W

matrix([[-0.20490976, -0.00898234],
        [-0.38714331, -0.58899857],
        [ 0.54648218,  0.25428655],
        [ 0.71378517, -0.76703217]])

In [179]:
data_set = new_df.to_numpy()

In [180]:
projections = np.dot(data_set,W)

In [181]:
projections

matrix([[-1.49220928, -1.90471019],
        [-1.25765567, -1.60841444],
        [-1.3487506 , -1.74984634],
        [-1.18024885, -1.63919094],
        [-1.51043263, -1.96271182],
        [-1.40183784, -2.22012479],
        [-1.27966155, -1.91802238],
        [-1.37835575, -1.81948345],
        [-1.11648646, -1.54502341],
        [-1.3131003 , -1.56518243],
        [-1.57646265, -1.99977595],
        [-1.28272558, -1.79225832],
        [-1.30854321, -1.53081299],
        [-1.37003298, -1.60260778],
        [-1.9385142 , -2.25635443],
        [-1.76617886, -2.56817609],
        [-1.62043071, -2.32183941],
        [-1.42083076, -1.98141341],
        [-1.49597495, -2.08721642],
        [-1.48232553, -2.13268433],
        [-1.35102322, -1.77221907],
        [-1.37223268, -2.15048769],
        [-1.6470616 , -2.0608335 ],
        [-1.03670041, -1.94073416],
        [-1.11878093, -1.71597236],
        [-1.16885021, -1.55845536],
        [-1.1809505 , -1.94746123],
        [-1.45805203, -1.880

In [182]:
projections.shape

(150, 2)

In [183]:
X = projections
y = df['Species']

In [184]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [185]:
from sklearn.model_selection import train_test_split

In [186]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 22)

In [187]:
X_train.shape

(120, 2)

In [188]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

C:\Python39\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Python39\lib\site-packages\sklearn\utils\validation.py:593: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [189]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9666666666666667

In [190]:
X_without_lda = new_df
X_without_lda

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [191]:
y_without_lda = df['Species']

In [192]:
y_without_lda

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [194]:
from sklearn.model_selection import train_test_split

In [196]:
X_train_without_lda, X_test_without_lda, y_train_without_lda, y_test_without_lda = train_test_split(X_without_lda,y_without_lda,test_size = 0.2,random_state=22)

In [197]:
X_train_without_lda

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
30             4.8           3.1            1.6           0.2
31             5.4           3.4            1.5           0.4
89             5.5           2.5            4.0           1.3
90             5.5           2.6            4.4           1.2
55             5.7           2.8            4.5           1.3
..             ...           ...            ...           ...
102            7.1           3.0            5.9           2.1
100            6.3           3.3            6.0           2.5
44             5.1           3.8            1.9           0.4
132            6.4           2.8            5.6           2.2
117            7.7           3.8            6.7           2.2

[120 rows x 4 columns]

In [198]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors = 5)
knn1.fit(X_train_without_lda,y_train_without_lda)
y_pred_without_lda = knn1.predict(X_test_without_lda)

In [199]:
y_pred_without_lda

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

In [200]:
accuracy_score(y_test_without_lda,y_pred_without_lda)

0.9666666666666667

In [ ]:
# The accuracy score remains the same with and without LDA as preprocessing step.